[package]
name = "rua"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# pest = "*"
# pest_derive = "*"
ordered-float = "2.0"

[[bin]]
name="rua"
path="src/bin/rua.rs"